name: Build all modules

on:
    push:
        branches:
        - main
        - dev
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'adopt'
            java-version: '21'
        - name: Build with Maven
          run: mvn clean compile package
