name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean compile package

      - name: List target directory
        run: ls -la target  # Проверяем, что файлы действительно созданы

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()  # Запускается только если предыдущий job успешен
    steps:
      - name: Deploy with SCP
        uses: appleboy/scp-action@v0.0.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "client/target/*.jar", "server/target/*.jar"
          target: "/home/${{ secrets.SSH_USERNAME }}/"
