name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean compile package

      - name: Combine JAR files
        run: |
          mkdir -p combined
          cp client/target/*.jar combined/
          cp server/target/*.jar combined/

      - name: List combined JAR files
        run: ls -la combined

      - name: Upload JAR files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: combined-jars
          path: combined/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Download JAR files
        uses: actions/download-artifact@v3
        with:
          name: combined-jars

      - name: List downloaded JAR files
        run: ls -la combined

      - name: Deploy with SCP
        uses: appleboy/scp-action@v0.0.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "combined/*.jar"
          target: "/home/${{ secrets.SSH_USERNAME }}/"
