name: Deploy jar files to SSH server via SCP

on:
    push:
        branches:
        - main
        - dev
    pull_request:
        branches:
        - main

jobs:
    deploy:
        depends-on: build
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'adopt'
            java-version: '21'
        - name: Deploy with SCP
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            source: "target/*.jar"
            target: "/home/${{ secrets.SSH_USERNAME }}/"