name: Sanity check using Checkstyle

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'adopt'
            java-version: '21'
        - name: Run Checkstyle
          run: mvn checkstyle:check